### PR TITLE
Lesson2

### PR DESCRIPTION
**Pull request by barbaradegraaf**
Lesson 2 has notes and two js codes that where used in problem sets (creating stairs and making a bird). Removed Lesson1 notes cause I by accident added them to the commit for Lesson 2 branch

### CODE REVIEW

**Comment by cathyatseneca** [comment]
can you also make a web page with it.  A plain html file that will load your bird.js?

**Comment by cathyatseneca** [comment]
when you finish it, you just need to push to the lesson 2 branch again.  Make a comment here so that I know its done.  then I will check and pull it in

**Comment by barbaradegraaf** [comment]
I have added a index html file to load the bird.js file. I have also changed the code on the drinking bird at the end to allow it to load in the html file.

**Comment by cathyatseneca** [comment]
When I run index.html, it does not seem to load.  no three.js file so you should put that in too.

**Comment by barbaradegraaf** [comment]
I have put up the three.js file in the js folder and have put up new index.html and bird.js files. It should load correctly now

**Pull request merged**
